# Generated by Django 3.0.5 on 2023-09-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20230912_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='product'),
            preserve_default=False,
        ),
    ]
